import os

absolute_path = os.path.dirname(os.path.abspath(__file__))    
f = open("commands.txt" , "w")

f = open(os.path.join(absolute_path, "commands.txt"), "w")

f.write("beginfill, black")
f.write("\n")
f.write("circle, 20, 1, black")
f.write("\n")
f.write("endfill")
f.write("\n")
f.write("penup")
f.write("\n")
f.write("goto, 120, 0, 1, black")
f.write("\n")
f.write("pendown")
f.write("\n")
f.write("beginfill, black")
f.write("\n")
f.write("circle, 20, 1, black")
f.write("\n")
f.write("endfill")
f.write("\n")
f.write("penup")
f.write("\n")
f.write("goto, 150, 40, 1, black")
f.write("\n")
f.write("pendown")
f.write("\n")
f.write("beginfill, yellow")
f.write("\n")
f.write("goto, -30, 40, 1, black")
f.write("\n")
f.write("goto, -30, 70, 1, black")
f.write("\n")
f.write("goto, 60, 70, 1, black")
f.write("\n")
f.write("goto, 60, 100, 1, black")
f.write("\n")
f.write("goto, 90, 100, 1, black")
f.write("\n")
f.write("goto, 115, 70, 1, black")
f.write("\n")
f.write("goto, 150, 70, 1, black")
f.write("\n")
f.write("goto, 150, 40, 1, black")
f.write("\n")
f.write("endfill")

f.close()
